name: google_maps_flutter_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - google_maps_flutter
  - google_maps_flutter/example
  - google_maps_flutter_android
  - google_maps_flutter_android/example
  - google_maps_flutter_ios
  - google_maps_flutter_ios/example/ios14
  - google_maps_flutter_ios/example/ios15
  - google_maps_flutter_ios/example/shared/maps_example_dart
  - google_maps_flutter_platform_interface
  - google_maps_flutter_web
  - google_maps_flutter_web/example
