name: video_player_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - video_player
  - video_player/example
  - video_player_android
  - video_player_android/example
  - video_player_avfoundation
  - video_player_avfoundation/example
  - video_player_platform_interface
  - video_player_web
  - video_player_web/example
