name: image_picker_for_web_example
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.22.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  image_picker_for_web:
    path: ../
  image_picker_platform_interface: ^2.8.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
